spring:
  main:
    banner-mode: 'off' #disable banner
  mvc:
    throw-exception-if-no-handler-found: true #disable spring's default exception handling
  profiles:
    active: dev # Set the active profile here
  jpa:
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true #Enable autoregistration of Jadira Usertypes
  web:
    resources:
      add-mappings: false
logging:
  config: classpath:logger/log4j2-${spring.profiles.active}.yml


server:
  port: 8086
  servlet:
    contextPath: /jpa-querydsl
